name: pr

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    # Build and run tests
    - run: |
        go get -v -t -d ./...
    - run: go test -v ./...
    - run: go build -a -v -ldflags="-extldflags=-static" -tags netgo,usergo,sqlite_omit_load_extension .
    - run: sha256sum ./wiregarden > SHA256SUMS
